site_name: TC组织 | TDR服务器
theme:
  name: material
  features:
    - header.autohide
    - announce.dismiss
    - navigation.instant
  icon:
    repo: fontawesome/brands/github
    edit: material/file-document-edit
  language: zh
  palette:
    - scheme: default
      primary: light blue
      accent: orange
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=AclOw9Bg
      name: TC组织QQ群
  generator: false
  

plugins:
  - tags

repo_url: https://github.com/hiyms/TCweb
repo_name: hiyms/TCweb
edit_uri: edit/master/docs/

extra_css:
  - stylesheets/extra.css